allowBuilds:
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@netlify/build@36.4.3'
  - '@netlify/functions-utils@7.1.6'
  - '@netlify/zip-it-and-ship-it@15.4.1'
  - '@next/env@16.3.4'
  - '@next/eslint-plugin-next@16.3.4'
  - '@next/swc-darwin-arm64@16.3.4'
  - '@next/swc-darwin-x64@16.3.4'
  - '@next/swc-linux-arm64-gnu@16.3.4'
  - '@next/swc-linux-arm64-musl@16.3.4'
  - '@next/swc-linux-x64-gnu@16.3.4'
  - '@next/swc-linux-x64-musl@16.3.4'
  - '@next/swc-win32-arm64-msvc@16.3.4'
  - '@next/swc-win32-x64-msvc@16.3.4'
  - eslint-config-next@16.3.4
  - netlify-cli@27.4.2
  - next@16.3.4
